### ISSUE TITLE
Cheatsheet - Link To Downloadable Scenariotool-Zip File Does Not Work

### ISSUE THREAD

**Issue by Albert7545** [ObiWanLansi/SIGENCE-Scenario-Tool#187]
In the Cheat Sheet (section: Installation), the link to https://github.com/ObiWanLansi/SIGENCE-Scenario-Tool/archive/master.zip does not work.
Cause:
   1. This link is not activated
   2. The sub-directory /archive is non-existent

Viele Grüße
Andre

**Comment by ObiWanLansi** [comment]
I Opend The Link In Word And Adobe Acrobat And It Worked.
But I Will Change The Link To The Official Link For The Releases In The Next Version.
