### ISSUE TITLE
Export to RFdevices (i.e. Excel Table) --> wrong values for RxTxType and AntennaType

### ISSUE THREAD

**Issue by Albert7545** [ObiWanLansi/SIGENCE-Scenario-Tool#188]
When exporting the scenario to an Excel File, values for RxTxType and AntennaType are incorrect (when the device ID is negative (i.e. for a receiver)):
e.g.: 
 - RxTxType value which was set to B200mini in the SIGENCE-Scenario-Tool was exported to 4242 in Excel (but 3 was expected)
 - AntennaType value which was set to OMNILOG30800  was exported to value 255 but 3 was expected according to Scenario file description

VG
Andre

**Comment by ObiWanLansi** [comment]
I Checked This With The Current Version (19) And The Result Is Follow:

- The RxTxType Is 3 ( As Expected)
- The AntennaType Is 1 ( 3 Is The SimradArgusRadar)

I Guess It Was Maybe Perhaps An Old Version Of The SST.
